# TAREFAS

Principais documentações:
- Dicionário PNADc Microdados 2025: para saber colunas e posições

In [4]:
%load_ext autoreload
%autoreload 2
    
import pandas as pd
import sys

sys.path.append('../src')
import data_treatment

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [5]:
dict_file = "dicionario_PNADC_microdados_2025_visita1_20260508.xls"
df_dict = data_treatment.load_pnad_dictionary(dict_file)
display(df_dict.head())

   start  size        var
2      1   4.0        Ano
3      5   1.0  Trimestre
4      6   2.0         UF
31     8   2.0    Capital
58    10   2.0    RM_RIDE

In [6]:
pnad_preview = "preview.txt"
df_pnad_preview = data_treatment.load_pnad_data(df_dict=df_dict, file=pnad_preview)
display(df_pnad_preview.head())

,Ano,Trimestre,UF,Capital,RM_RIDE,UPA,Estrato,V1008,V1014,V1022,...,V1032191,V1032192,V1032193,V1032194,V1032195,V1032196,V1032197,V1032198,V1032199,V1032200
0,2025,3,53,53,NaN,530095618,5310112,06,12,1,...,000000.00000000,001152.11414663,001076.96027323,000581.89322886,001708.73280144,000580.32487648,000000.00000000,000000.00000000,000000.00000000,000538.09127016
1,2025,1,31,NaN,NaN,310596270,3154011,06,12,1,...,000000.00000000,001776.10594374,000000.00000000,000000.00000000,001726.66561030,000834.52392832,000854.40785106,001714.80455236,000846.09045294,000835.81649885
2,2025,3,53,53,NaN,530083357,5310220,01,12,2,...,000000.00000000,000000.00000000,000211.63790970,000217.51858920,000439.31076253,000228.16377326,000207.57306338,000438.27099190,000000.00000000,000216.61113250
3,2025,1,27,NaN,NaN,270029922,2752020,08,12,2,...,000131.02258144,000000.00000000,000255.25179889,000000.00000000,000132.93345868,000000.00000000,000000.00000000,000000.00000000,000000.00000000,000000.00000000
4,2025,4,22,NaN,NaN,220149103,2252012,01,13,1,...,000407.14360564,000399.72208129,000000.00000000,000420.10021380,000416.98259083,000797.90589713,000000.00000000,000000.00000000,000000.00000000,000000.00000000

## Definição do filtro de áreas urbanas

*“Three types of urban sectors as classified by IBGE (urbanized urban areas, non-urbanized urban areas and isolated urban areas) plus the areas classified as rural of urban extension, that correspond roughly to the urban fringe and are highly interconnected and share several attributes with urbanized areas.”* (pg. 17)

**Fonte:**
</br> Variável: Situação do domicílio

**Tratamento:**
</br>
Definir função que filtre a tabela para considerar apenas áreas urbanas em escopo

## Criar um identificador dos domicílios

Para otimizar o tratamento dos dados contanto com o alto volume, vai ser preciso particionar em subsets, e usar uma chave de identificação dos domicílios pra relacionar
Estudar como funciona as Unidades Primárias de Amostragem
Estudar se esse identificador existe na basedosdados

**Fonte:**
</br> Variáveis:
- Estrato
- Número de seleção do domicílio

## Distribuição das opções de condição de ocupação da moradia

*"we have used information on the dwelling mode of occupancy, land property rights and sector type to define the tenure categories [...]. Based on the above variables defined four different tenure status were defined: i) formal owners: he owns the house, owns the land and the dwelling unit is not located in a substandard area; ii) formal renter: rents or rent-free outside substandard area; iii) informal owners: owns the house but not the land or has other tenure condition such as encroachment (squatters), owns in a substandard area (slum dweller) or both; and iv) informal renter: rents in a substandard area."* (pg. 17)

Tentar achar mais definição de cada opção a partir das variáveis

**Fonte:**
</br> Variáveis:
- Este domicílio é do tipo: (SA01001)
- Este domicílio é: (S01017)
- O terreno onde está localizado esse domicílio é próprio? (S01020)
- Esse domicílio tem algum documento que prove sua propriedade? (S01020A)

**Tratamento:**
</br>
Criar um subset do conjunto de dados com uma key e as variáveis ligadas à definição das opções
Definir função que categoriza cada domicílio em alguma das opções
Criar uma tabela de distribuição dessas opções, assim como no artigo